/* ============================================================
   Radio Cafe — بيانات المنيو
   هذا الملف تكتبه لوحة التحكم. عدّل الأسعار والتوفّر من /admin
   وليس من هنا، حتى لا يضيع التعديل مع أول حفظ من اللوحة.

   soldout: true  =  الصنف غير متوفّر اليوم (يظهر بالمنيو ولا يُطلب)
   الأسعار لمّا توصل بعد — أدخلها من اللوحة أو ابعثها ليُكتب دفعة واحدة.
   ============================================================ */
const MENU_VERSION = 1788531298227;
const P = [
  {"img":"mojito-blueberry.webp","cat":"mojito","ar":"موهيتو بلو بيري","en":"Blueberry Mojito","d":"توت أزرق منعش على الثلج.","price":"150"},
  {"img":"mojito-strawberry.webp","cat":"mojito","ar":"موهيتو فراولة","en":"Strawberry Mojito","d":"فراولة منعشة مع النعناع.","price":"150","star":true},
  {"img":"mojito-lemon-mint.webp","cat":"mojito","ar":"موهيتو ليمون ونعناع","en":"Lemon & Mint Mojito","d":"ليمون ونعناع طازج على الثلج.","price":"150","star":true},
  {"img":"mojito-kiwi.webp","cat":"mojito","ar":"موهيتو كيوي","en":"Kiwi Mojito","d":"كيوي أخضر منعش.","price":"150"},
  {"img":"mojito-watermelon.webp","cat":"mojito","ar":"موهيتو بطيخ","en":"Watermelon Mojito","d":"بطيخ منعش على الثلج.","price":"150"},
  {"img":"mojito-cherry.webp","cat":"mojito","ar":"موهيتو كرز","en":"Cherry Mojito","d":"كرز بطعم غني ومنعش.","price":"150"},
  {"img":"shake-oreo.webp","cat":"shake","ar":"ميلك شيك اوريو","en":"Oreo Milkshake","d":"حليب مخفوق بقطع الأوريو.","price":"200","star":true},
  {"img":"shake-vanilla.webp","cat":"shake","ar":"ميلك شيك فانيلا","en":"Vanilla Milkshake","d":"فانيلا كريمية كلاسيكية.","price":"200"},
  {"img":"shake-pistachio.webp","cat":"shake","ar":"ميلك شيك بستاشيو","en":"Pistachio Milkshake","d":"فستق حلبي كريمي.","price":"200"},
  {"img":"shake-lotus.webp","cat":"shake","ar":"ميلك شيك لوتس","en":"Lotus Milkshake","d":"بسكويت لوتس كراميلي.","price":"200","star":true},
  {"img":"shake-strawberry.webp","cat":"shake","ar":"ميلك شيك فراولة","en":"Strawberry Milkshake","d":"فراولة طازجة ومثلجة.","price":"200"},
  {"img":"shake-coconut.webp","cat":"shake","ar":"ميلك شيك جوز الهند","en":"Coconut Milkshake","d":"جوز الهند بطعم استوائي.","price":"200"},
  {"img":"shake-kinder.webp","cat":"shake","ar":"ميلك شيك كيندر","en":"Kinder Milkshake","d":"حليب مخفوق بشوكولا كيندر.","price":"200"},
  {"img":"shake-chocolate.webp","cat":"shake","ar":"ميلك شيك شوكولا","en":"Chocolate Milkshake","d":"شوكولا غنية ومثلجة.","price":"200"},
  {"img":"shake-banana.webp","cat":"shake","ar":"ميلك شيك موز","en":"Banana Milkshake","d":"موز طازج مع الحليب.","price":"200"},
  {"img":"shake-berry.webp","cat":"shake","ar":"ميلك شيك توت","en":"Berry Milkshake","d":"توت مخفوق ومنعش.","price":"200"},
  {"img":"shake-milk.webp","cat":"shake","ar":"ميلك شيك حليب","en":"Classic Milkshake","d":"حليب مخفوق كريمي.","price":"200"},
  {"img":"sweet-bubbly-chocolate.webp","cat":"sweets","ar":"بابلي شوكولا","en":"Chocolate Bubble Waffle","d":"بابل وافل طازج بالشوكولا.","price":"200"},
  {"img":"sweet-bubbly-white.webp","cat":"sweets","ar":"بابلي وايت","en":"White Chocolate Bubble Waffle","d":"بابل وافل بالشوكولا البيضاء.","price":"200"},
  {"img":"sweet-bubbly-pistachio.webp","cat":"sweets","ar":"بابلي بستاشيو","en":"Pistachio Bubble Waffle","d":"بابل وافل بكريمة الفستق.","price":"200"},
  {"img":"sweet-bubbly-mix.webp","cat":"sweets","ar":"بابلي مكس","en":"Mixed Bubble Waffle","d":"بابل وافل بخلطة النكهات.","price":"200","star":true},
  {"img":"sweet-crepe-chocolate.webp","cat":"sweets","ar":"كريب شوكولا","en":"Chocolate Crepe","d":"كريب رقيق محشو بالشوكولا.","price":"200"},
  {"img":"sweet-crepe-fruit.webp","cat":"sweets","ar":"كريب فواكه","en":"Fruit Crepe","d":"كريب بالفواكه الطازجة.","price":"200"},
  {"img":"sweet-crepe-caramel.webp","cat":"sweets","ar":"كريب كراميل","en":"Caramel Crepe","d":"كريب بصلصة الكراميل.","price":"200"},
  {"img":"sweet-crepe-pistachio.webp","cat":"sweets","ar":"كريب بستاشيو","en":"Pistachio Crepe","d":"كريب بكريمة الفستق الحلبي.","price":"200","star":true},
  {"img":"sweet-cake-chocolate.webp","cat":"sweets","ar":"ميني بان كيك شوكولا","en":"Chocolate Mini Pancakes","d":"ميني بان كيك بصوص الشوكولا.","price":"200"},
  {"img":"sweet-cake-strawberry.webp","cat":"sweets","ar":"ميني بان كيك فراولة","en":"Strawberry Mini Pancakes","d":"ميني بان كيك بالفراولة الطازجة.","price":"200"},
  {"img":"sweet-cake-pistachio.webp","cat":"sweets","ar":"ميني بان كيك بستاشيو","en":"Pistachio Mini Pancakes","d":"ميني بان كيك بكريمة الفستق.","price":"200"},
  {"img":"hot-espresso.webp","cat":"hot","ar":"أسبريسو","en":"Espresso","d":"جرعة مركزة من أجود حبوب البن.","price":"50"},
  {"img":"hot-americano.webp","cat":"hot","ar":"أمريكانو","en":"Americano","d":"إسبريسو ممدود بالماء الساخن.","price":"50"},
  {"img":"hot-latte.webp","cat":"hot","ar":"لاتيه","en":"Latte","d":"حليب مبخر ناعم فوق إسبريسو.","price":"100"},
  {"img":"hot-mocha.webp","cat":"hot","ar":"موكا","en":"Mocha","d":"إسبريسو وشوكولا وحليب.","price":"75"},
  {"img":"hot-mocha-latte.webp","cat":"hot","ar":"لاتيه موكا","en":"Mocha Latte","d":"لاتيه بلمسة شوكولا.","price":"100"},
  {"img":"hot-caramel-espresso.webp","cat":"hot","ar":"أسبريسو كراميل","en":"Caramel Espresso","d":"إسبريسو بلمسة كراميل ذهبية.","price":"50"},
  {"img":"hot-turkish.webp","cat":"hot","ar":"قهوة تركية (غلي)","en":"Turkish Coffee","d":"قهوة تركية على الطريقة التقليدية.","price":"75"},
  {"img":"hot-avocado-espresso.webp","cat":"hot","ar":"أسبريسو أفوكادو","en":"Avocado Espresso","d":"إسبريسو مع كريمة الأفوكادو.","price":"125"},
  {"img":"hot-arabic-coffee.webp","cat":"hot","ar":"قهوة عربية","en":"Arabic Coffee","d":"قهوة عربية بالهيل.","price":"50"},
  {"img":"hot-3in1.webp","cat":"hot","ar":"3 في 1","en":"3 in 1","d":"قهوة سريعة بطعم متكامل.","price":"50"},
  {"img":"hot-tea.webp","cat":"hot","ar":"شاي","en":"Tea","d":"شاي ساخن.","price":"40"},
  {"img":"hot-karak.webp","cat":"hot","ar":"شاي كرك","en":"Karak Tea","d":"شاي بالحليب والبهارات.","price":"100"},
  {"img":"hot-cappuccino.webp","cat":"hot","ar":"كابتشينو","en":"Cappuccino","d":"إسبريسو مع رغوة حليب مخملية.","price":"50"},
  {"img":"hot-chocolate.webp","cat":"hot","ar":"هوت شوكلت","en":"Hot Chocolate","d":"شوكولا ساخنة كريمية.","price":"50"},
  {"img":"cold-iced-latte.webp","cat":"cold","ar":"أيس لاتيه","en":"Iced Latte","d":"لاتيه بارد منعش على الثلج.","price":"150"},
  {"img":"cold-spanish-latte.webp","cat":"cold","ar":"أيس سبانيش لاتيه","en":"Iced Spanish Latte","d":"لاتيه مثلج بالحليب المكثف.","price":"200"},
  {"img":"cold-mocha-latte.webp","cat":"cold","ar":"أيس لاتيه موكا","en":"Iced Mocha Latte","d":"لاتيه بارد بالشوكولا.","price":"200"},
  {"img":"cold-white-mocha.webp","cat":"cold","ar":"أيس وايت موكا","en":"Iced White Mocha","d":"وايت موكا مثلجة كريمية.","price":"200"},
  {"img":"cold-radio-latte.webp","cat":"cold","ar":"أيس لاتيه راديو","en":"Radio Iced Latte","d":"خلطة راديو الخاصة على الثلج.","price":"200"},
  {"img":"cold-blueberry-latte.webp","cat":"cold","ar":"أيس لاتيه بلو بيري","en":"Blueberry Iced Latte","d":"لاتيه بارد بنكهة التوت الأزرق.","price":"200"},
  {"img":"cold-v60.webp","cat":"cold","ar":"أيس V60","en":"Iced V60","d":"تقطير V60 على الثلج.","price":"220"},
  {"img":"cold-americano.webp","cat":"cold","ar":"أيس أمريكانو","en":"Iced Americano","d":"أمريكانو بارد منعش.","price":"150"},
  {"img":"cold-vanilla-latte.webp","cat":"cold","ar":"أيس لاتيه فانيلا","en":"Vanilla Iced Latte","d":"لاتيه بارد بالفانيلا.","price":"200"},
  {"img":"cold-frappuccino.webp","cat":"cold","ar":"أيس فرابتشينو","en":"Frappuccino","d":"قهوة مخفوقة مثلجة بالكريمة.","price":"200"},
  {"img":"cold-caramel.webp","cat":"cold","ar":"أيس كراميل","en":"Iced Caramel","d":"قهوة باردة بصلصة الكراميل.","price":"200"},
  {"img":"juice-strawberry.webp","cat":"juice","ar":"عصير فراولة","en":"Strawberry Juice","d":"فراولة طازجة معصورة.","price":"150"},
  {"img":"juice-polo.webp","cat":"juice","ar":"عصير بولو","en":"Polo Juice","d":"خلطة الحمضيات المنعشة.","price":"150"},
  {"img":"juice-mixed.webp","cat":"juice","ar":"عصير فواكه","en":"Mixed Fruit Juice","d":"خليط فواكه طازجة.","price":"175"},
  {"img":"juice-strawberry-pineapple.webp","cat":"juice","ar":"عصير فريز وأناناس","en":"Strawberry & Pineapple","d":"فراولة مع أناناس طازج.","price":"175"},
  {"img":"juice-pineapple.webp","cat":"juice","ar":"عصير أناناس","en":"Pineapple Juice","d":"أناناس طازج معصور.","price":"150"},
  {"img":"juice-mango.webp","cat":"juice","ar":"عصير مانجو","en":"Mango Juice","d":"مانجو استوائية كريمية.","price":"175"},
  {"img":"juice-avocado-cream.webp","cat":"juice","ar":"أفوكادو قشطة","en":"Avocado & Cream","d":"أفوكادو مخفوق مع القشطة.","price":"175","star":true},
  {"img":"juice-avocado-chocolate.webp","cat":"juice","ar":"أفوكادو شوكولا","en":"Avocado & Chocolate","d":"أفوكادو مع صوص الشوكولا.","price":"150"},
  {"img":"juice-avocado-fruit.webp","cat":"juice","ar":"أفوكادو فواكه","en":"Avocado & Fruit","d":"أفوكادو مع خليط الفواكه.","price":"150"},
  {"img":"juice-avocado-mix.webp","cat":"juice","ar":"أفوكادو مكس","en":"Avocado Mix","d":"أفوكادو بكل الإضافات.","price":"200"},
  {"img":"panpop-cake-pistachio.webp","cat":"panpop","ar":"بانبوب كيك بستاشيو","en":"PanPop Pistachio Cake","d":"كيك بانبوب بكريمة الفستق.","price":"150"},
  {"img":"panpop-cake-chocolate.webp","cat":"panpop","ar":"بانبوب كيك شوكولا","en":"PanPop Chocolate Cake","d":"كيك بانبوب بالشوكولا.","price":"150"},
  {"img":"panpop-cake-bluehawaii.webp","cat":"panpop","ar":"بانبوب كيك بلو هاواي","en":"PanPop Blue Hawaii Cake","d":"كيك بانبوب بنكهة بلو هاواي.","price":"150"},
  {"img":"panpop-cake-white.webp","cat":"panpop","ar":"بانبوب كيك وايت","en":"PanPop White Cake","d":"كيك بانبوب بالشوكولا البيضاء.","price":"150"},
  {"img":"panpop-cake-strawberry.webp","cat":"panpop","ar":"بانبوب كيك فريز","en":"PanPop Strawberry Cake","d":"كيك بانبوب بالفراولة.","price":"150"},
  {"img":"panpop-cheesecake.webp","cat":"panpop","ar":"تشيز كيك بانبوب","en":"PanPop Cheesecake","d":"تشيز كيك بانبوب كريمي بالطبقة الهشة.","price":"150","star":true},
  {"img":"panpop-cheesecake-strawberry.webp","cat":"panpop","ar":"تشيز كيك فريز","en":"Strawberry Cheesecake","d":"تشيز كيك بطبقة الفراولة.","price":"150"},
  {"img":"panpop-cheesecake-lotus.webp","cat":"panpop","ar":"تشيز كيك لوتس","en":"Lotus Cheesecake","d":"تشيز كيك ببسكويت لوتس.","price":"200"},
  {"img":"panpop-cheesecake-pistachio.webp","cat":"panpop","ar":"تشيز كيك بستاشيو","en":"Pistachio Cheesecake","d":"تشيز كيك بكريمة الفستق.","price":"150"}
];
